Added TypeOrm, Added user table, added swagger config
vention-js-lab/invention-stayhub-backend pull request #1
Opened 2024-11-06 12:41 UTC by Savesh1508

- Added TypeORM
- Added user table
- Added swagger config
- Added validation config
- Added env config

Before all:
You should create Database using terminal or on PgAdmin

- Put the database name which you create in .env file (DB_NAME)
- Create and fill .env file

Mention:
The REFRESH_MS option in .env is the lifetime of the refresh token in cookies, you can write there 2592000000

## Migration 
- npm run migration:generate -- src/database/migrations/name_of_migration
- npm run migration:run
- npm run migration:revert

2024-11-06 15:02 UTC, Aziza-Azizova commented
need to add a migration for these changes

2024-11-06 16:11 UTC, ShahobiddinIsmoilov approved these changes

2024-11-06 16:20 UTC, NegatiV-64 requested changes
Please add migrations for the table

2024-11-06 19:19 UTC, NegatiV-64 commented on src/main.ts
> +    console.log(error);
Why to have here try catch? I think that it is not needed

2024-11-06 19:22 UTC, NegatiV-64 commented on src/modules/user/entity/user.entity.ts
> +import { Roles } from '../../../shared/constants/user-roles.constants';
Configure the import aliases, otherwise the imports are unreadable

2024-11-06 19:22 UTC, NegatiV-64 commented on src/modules/user/entity/user.entity.ts
> +  @Column()
I suggest to use the snake case for column names

2024-11-06 19:22 UTC, NegatiV-64 commented on src/modules/user/user.controller.ts
> +export class UserController {
What's the point of having the controller?

2024-11-07 08:53 UTC, NegatiV-64 requested changes

2024-11-07 08:53 UTC, NegatiV-64 commented on package.json
> +    "typeorm": "npx typeorm -d dist/shared/configs/datasource.js",
Don't use the dist folder, it is not good practice

2024-11-07 08:53 UTC, NegatiV-64 commented on package.json
> +    "cookie-parser": "^1.4.7",
Why do you need it?

2024-11-07 08:53 UTC, NegatiV-64 commented on src/modules/user/entity/user.entity.ts
> +  first_name: string;
Use camelCase for model property, use snake_case for DB column

2024-11-07 08:53 UTC, NegatiV-64 commented on src/modules/user/user.controller.ts
Why this class is needed?

2024-11-07 08:53 UTC, NegatiV-64 commented on src/modules/user/user.service.ts
Why we need this class?

2024-11-07 08:53 UTC, NegatiV-64 commented on src/shared/configs/database.config.ts
> +  username: configService.getOrThrow('DB_USER'),
Don't use getOrThrow, just use get. You are validating the config during the app start

2024-11-07 08:53 UTC, NegatiV-64 commented on src/shared/configs/datasource.ts
> +@Module({
Why it is a module?

2024-11-07 08:53 UTC, NegatiV-64 commented on tsconfig.json
> +      "*": ["*"]
User # or @ instead of *

2024-11-07 10:33 UTC, farruholimov reviewed
Too many changes for only one PR. One PR should contain changes for a single task.

2024-11-07 12:30 UTC, NegatiV-64 approved these changes

2024-11-07 12:30 UTC, merged