[INV-23] Added Docker Containering
vention-js-lab/invention-stayhub-backend pull request #14
Opened 2024-11-10 20:22 UTC by Savesh1508

2024-11-12 05:04 UTC, Savesh1508 commented
![Screenshot_1](https://github.com/user-attachments/assets/46f29927-4766-494b-a030-a5b6d7137e52)
![Screenshot_2](https://github.com/user-attachments/assets/170f2143-0f83-4a13-8b7e-19ea9f231550)
![Screenshot_3](https://github.com/user-attachments/assets/b19f69fa-28f7-4b4d-ab89-bf2d28f43b2e)

2024-11-12 05:12 UTC, NegatiV-64 requested changes

2024-11-12 05:12 UTC, NegatiV-64 commented on docker-compose.yml
> +    image: postgres:14
14? Why not 17 or 16 at least?

2024-11-12 05:12 UTC, NegatiV-64 commented on tsconfig.json
> +  "include": [
Why it was added? No need to modify the tsconfig

2024-11-12 05:12 UTC, NegatiV-64 commented on Dockerfile
> +FROM node:20-alpine
Use 22 lts

2024-11-12 05:12 UTC, NegatiV-64 commented on Dockerfile
> +CMD ["npm", "run", "start:prod"]
Devide the build into steps please

2024-11-12 08:00 UTC, NegatiV-64 requested changes

2024-11-12 08:00 UTC, NegatiV-64 commented on package.json
> +    "start:prod": "node dist/src/main",
Don't change it

2024-11-12 08:00 UTC, NegatiV-64 commented on package.json
> +    "start:prod": "node dist/src/main",
Make sure that Docker correctly copies the folder and files

2024-11-18 07:42 UTC, NegatiV-64 requested changes

2024-11-18 07:42 UTC, NegatiV-64 commented on Dockerfile
> +ENV APP_ENV=production
I meant not APP ENV but NODE_ENV

2024-11-18 07:42 UTC, NegatiV-64 commented on Dockerfile
> +ENV APP_ENV=production
Please see comment above

2024-11-18 07:42 UTC, NegatiV-64 commented on Dockerfile
> +RUN npx tsc database/migrations/*.ts --outDir dist/database/migrations
Why do you need to compile them?

2024-11-18 07:42 UTC, NegatiV-64 commented on docker-compose.yml
> +      - '${APP_PORT}:${APP_PORT}'
I think that in EXPOSE in Dockerfile, you are writing 3000, why here it depends on the APP PORT?

2024-11-18 07:42 UTC, NegatiV-64 commented on docker-compose.yml
> +      sh -c "npx typeorm-ts-node-commonjs migration:run -d /app/dist/typeorm.config.js && npm run start:prod"
typeorm-ts-node-commonjs can run ts files

2024-11-18 14:58 UTC, closed without merging