[INV-68]-Create method-to-create-accommodation
vention-js-lab/invention-stayhub-backend pull request #21
Opened 2024-11-13 14:39 UTC by blackseriesC63

Post <img width="2168" alt="Screenshot 2024-11-13 at 19 38 37" src="https://github.com/user-attachments/assets/0deb3ae7-aadd-4c49-977e-3d705477bce3">
Result <img width="2168" alt="Screenshot 2024-11-13 at 19 38 44" src="https://github.com/user-attachments/assets/dee86386-a7ed-40ba-9569-3d05458a367f">

2024-11-13 15:09 UTC, NegatiV-64 requested changes
Good job, left some comments + add Swagger API support for the responses

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +  // Route to create an address for an accommodation
Please remove the comment

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +  // Route to add images to an accommodation
Please remove the comment

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +    if (createAccommodationDto.amenity) {
I think that this check is redundant

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +  async createAddress(
Not sure that we need this endpoint. Address is created when accommodation is created

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +  async createAmenity(
Not sure that we need this endpoint. Amenities are created when accommodation is created

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +  @JoinColumn({ name: 'accommodation_id' }) // Explicitly define the column name here
Remove the comments

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +    if (createAccommodationDto.address) {
This check is redundant

2024-11-13 15:09 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +    const savedAccommodation =
Also we need to save the amenities right here

2024-11-13 15:13 UTC, ShahobiddinIsmoilov requested changes

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +  @JoinColumn({ name: 'accommodation_id' }) // Explicitly define the column name here
Please remove comments

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +  @Column({ name: 'accommodation_id' }) // Explicitly define the accommodation_id column
Please remove comments

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +  hasWifi: boolean;
Please make this optional too

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +  hasParking: boolean;
Please make this optional too

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +  createdAt: Date;
Please remove this field

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +  updatedAt: Date;
Please remove this field

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation.req.ts
> +  @IsOptional() // Make this optional if it might not always be provided
Please remove comments

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation.req.ts
> +  ownerId: string;
I guess we will take owner ID from request.user

2024-11-13 15:13 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/entities/accommodation-address.entity.ts
> +  zip_code: string;
Please change it back. Old version was correct

2024-11-13 20:05 UTC, ShahobiddinIsmoilov requested changes

2024-11-13 20:05 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +    if (!ownerId) {
I think this check is unnecessary

2024-11-13 20:05 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +      throw new Error('Account ID is missing in the request');
Also, wrong handling of the error. You should throw ```UnauthorizedException```, not pure ```Error```

2024-11-13 20:05 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +import { GetAccount } from '../../auth/decorators/get-account.decorator';
Bad import path

2024-11-13 20:05 UTC, ShahobiddinIsmoilov commented on src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
> +AccommodationAmenityDto;
Why do we need this?

2024-11-14 05:57 UTC, ShahobiddinIsmoilov approved these changes

2024-11-14 06:01 UTC, ShahobiddinIsmoilov submitted a review, later dismissed

2024-11-14 07:42 UTC, NegatiV-64 commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +@UseGuards(AccessTokenGuard)
Move guard to the methods level. We don't need to guard every route here

2024-11-14 07:44 UTC, NegatiV-64 requested changes

2024-11-14 07:44 UTC, NegatiV-64 commented on src/modules/accommodations/controllers/accommodations.controller.ts
> +@UseGuards(AccessTokenGuard)
Move guard to the methods level. We don't need to guard every route here

2024-11-14 07:44 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +    return createdAccommodation;
Would it have the address, images & amenities?

2024-11-14 08:14 UTC, NegatiV-64 approved these changes

2024-11-14 08:14 UTC, merged