[INV 70] CRUD operations for Accommodation/Update
vention-js-lab/invention-stayhub-backend pull request #27
Opened 2024-11-16 13:23 UTC by Aziza-Azizova

## Description:
- Added the ability for owners to update accommodation details (basic data, amenities, address).
- Ensured only the owner can perform updates by checking ownership.
- Included validations for the input data.

_P.S. Image update is the only part remaining._

## Screenshots
### Created accommodation details:
![image](https://github.com/user-attachments/assets/d89eb9d7-53a1-41a8-b0d9-63b50ca1ffd7)

### Updated details:
![image](https://github.com/user-attachments/assets/36fb9e7f-ef11-47c7-8422-fa23b20e9c62)

2024-11-16 18:33 UTC, Aziza-Azizova commented on src/modules/accommodations/services/accommodations.service.ts
> +    if (accommodation.ownerId !== ownerId) {
This is already handled in the getAccommodationById function. Should I check in this function as well?

2024-11-17 08:53 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +    if (accommodation.ownerId !== ownerId) {
Please do

2024-11-17 08:54 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +    if (accommodation.ownerId !== ownerId) {
In that case, no need

2024-11-17 15:50 UTC, NegatiV-64 commented on src/modules/accommodations/dto/requests/update-accommodation.req.ts
> +  price?: number;
Please use undefined explicitly instead of ? optional operator. Make sure that all fields are updated accordingly

2024-11-18 04:00 UTC, SurajSulten requested changes

2024-11-18 04:00 UTC, SurajSulten commented on src/modules/accommodations/services/accommodations.service.ts
> +    console.log(definedDetails);
why there is console.log? I think you should remove it

2024-11-18 07:45 UTC, NegatiV-64 requested changes

2024-11-18 10:16 UTC, SurajSulten submitted a review, later dismissed

2024-11-18 13:49 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +interface UpdateAccommodationParams {
Move into the types folder. Name the file accommodations-service.type.ts

2024-11-18 13:49 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +interface UpdateAccommodationParams {
Types folder of the accommodations module

2024-11-18 14:12 UTC, NegatiV-64 approved these changes

2024-11-18 14:13 UTC, merged