[INV-86] Create review module, entity and migration
vention-js-lab/invention-stayhub-backend pull request #37
Opened 2024-11-20 18:34 UTC by muhammadjon8

![image](https://github.com/user-attachments/assets/831a39dd-a1aa-42f2-b3c5-d602beeb9d30)

2024-11-21 05:05 UTC, NegatiV-64 requested changes

2024-11-21 05:05 UTC, NegatiV-64 commented on database/migrations/1732127232754-create-review-entity.ts
> +            isNullable: true,
It shouldn't be nullable

2024-11-21 05:05 UTC, NegatiV-64 commented on database/migrations/1732127232754-create-review-entity.ts
> +            isNullable: true,
It shouldn't be nullable

2024-11-21 05:05 UTC, NegatiV-64 commented on database/migrations/1732127232754-create-review-entity.ts
> +            isNullable: true,
It shouldn't be nullable

2024-11-21 05:08 UTC, NegatiV-64 commented on src/modules/review/entities/review.entity.ts
> +  @ManyToOne(() => Booking, { onDelete: 'SET NULL' })
If you want to reset to null, then you should actually fix the Typescript types for the entity

2024-11-21 11:21 UTC, farrooh requested changes

2024-11-21 11:21 UTC, farrooh commented on database/migrations/1732127232754-create-review-entity.ts
> +        onDelete: 'SET NULL',
It's more logical to cascade delete reviews. Who needs a review that doesn't have accommodation?

2024-11-21 18:52 UTC, NegatiV-64 approved these changes

2024-11-22 07:18 UTC, farrooh approved these changes

2024-11-22 07:19 UTC, merged