[INV-58] Create an endpoint to pay for a booking using Stripe
vention-js-lab/invention-stayhub-backend pull request #44
Opened 2024-11-27 12:43 UTC by ShahobiddinIsmoilov

2024-11-29 00:23 UTC, farrooh requested changes
1) Add a unique constraint for bookingID in the payment table if there won't be several transactions for a single booking.
2) Make it impossible to delete completed (already made payment) bookings. Their userID should be set to null if the user is deleted. And make bookingID not null in the payment table. Payments must have an entity.

2024-11-29 00:23 UTC, farrooh commented on src/modules/payments/services/payments.service.ts
> +    const paymentRecord = this.paymentRepository.findOneBy({ bookingId });
Will a new transaction be created if one is failed? 
As I understand from your code in payment.service, the answer is no, so you must add a unique constraint for bookingId to the payment table in DB. 
But if yes, there might be multiple transactions for a single booking, then you should add status checking too here.

2024-11-29 00:23 UTC, farrooh commented on src/modules/payments/services/payments.service.ts
> +      : newPaymentRecord;
Or just say `= existingPaymentRecord || newPaymentRecord;`

2024-11-29 08:13 UTC, NegatiV-64 requested changes

2024-11-29 08:13 UTC, NegatiV-64 commented on src/modules/payments/services/stripe.service.ts
> +export class StripeService {
I'd call it CheckoutService

2024-11-29 08:13 UTC, NegatiV-64 commented on src/modules/payments/services/stripe.service.ts
> +      throw new BadRequestException('Booking does not exist');
I think that BadRequest could make sense

2024-11-29 08:13 UTC, NegatiV-64 commented on src/modules/payments/services/stripe.service.ts
> +    switch (event.type) {
I think that map could be a better solution

2024-11-29 08:13 UTC, NegatiV-64 commented on src/shared/extractors/payment-intent.extractor.ts
Move it to the payment module, why it is on the shared level?

2024-11-29 08:13 UTC, NegatiV-64 commented on src/shared/utils/cors.util.ts
It should be inside the config, it is not a real utility

2024-12-05 05:03 UTC, Savesh1508 commented
Bro, in the next time, let's do huge renamings in the another pr. som many files changed so it's painful to check what I want

2024-12-05 05:21 UTC, NegatiV-64 approved these changes

2024-12-05 07:55 UTC, merged