[INV-95] Add wishlist functionality for Accommodation Card
vention-js-lab/invention-stayhub-backend pull request #50
Opened 2024-12-03 07:53 UTC by ShahobiddinIsmoilov

# Pull request for: [INV-95]

## Description

This pull request updates the response coming from list accommodations endpoint.

### Main changes:
* Created ```OptionalAccessTokenGuard``` for endpoints that should behave differently based on request authentication state.
* Added boolean ```isSavedToWishlist``` property to the ```Accommodation``` objects being returned.

### Demonstration
![image](https://github.com/user-attachments/assets/9d468c6f-ad8a-4459-8e88-3a6dfdf21ca2)

## Checklist

- [x] I have manually tested the changes and related features
- [x] I have run the linter and fixed any possible issues
- [x] I have run the tests and fixed any possible issues
- [x] I have run the build and fixed any possible issues

2024-12-04 06:07 UTC, NegatiV-64 requested changes
Don't mix the endpoints and services. Better to have duplicate code that spaghetti code with 100500 if/else or ambiguity

2024-12-04 06:07 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +    if (accountId) {
Why it's needed?

2024-12-04 06:07 UTC, NegatiV-64 commented on src/modules/accommodations/services/accommodations.service.ts
> +      queryBuilder.leftJoinAndSelect('accommodation.wishlist', 'wishlist', 'wishlist.accountId = :accountId', { accountId });
Better to offload the functionality to separate method/service

2024-12-04 06:07 UTC, NegatiV-64 commented on src/modules/auth/auth.module.ts
> +  providers: [AuthService, GoogleStrategy, AccessTokenStrategy, RefreshTokenStrategy, OptionalAccessTokenStrategy],
Why?

2024-12-04 06:07 UTC, NegatiV-64 commented on src/modules/auth/strategies/optional-access-token.strategy.ts
I don't think that we need this endpoint

2024-12-04 06:07 UTC, NegatiV-64 commented on src/shared/decorators/get-optional-account.decorator.ts
I don't think that we need this guard

2024-12-04 06:07 UTC, NegatiV-64 commented on src/shared/configs/jwt-auth.config.ts
> +  OptionalAccessTokenKey: 'optional-access-token',
No need for this

2024-12-04 06:07 UTC, NegatiV-64 commented on src/shared/guards/optional-access-token.guard.ts
Don't think that we need it

2024-12-05 08:48 UTC, ShahobiddinIsmoilov commented on src/modules/auth/auth.module.ts
> +  providers: [AuthService, GoogleStrategy, AccessTokenStrategy, RefreshTokenStrategy, OptionalAccessTokenStrategy],
> Why?

Removed

2024-12-05 08:49 UTC, ShahobiddinIsmoilov commented on src/modules/auth/strategies/optional-access-token.strategy.ts
> I don't think that we need this endpoint

Removed

2024-12-05 08:49 UTC, ShahobiddinIsmoilov commented on src/shared/configs/jwt-auth.config.ts
> +  OptionalAccessTokenKey: 'optional-access-token',
> No need for this

Removed

2024-12-09 09:32 UTC, NegatiV-64 approved these changes

2024-12-09 09:32 UTC, merged